# Generated by Django 6.0 on 2025-12-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField()),
                ('opponent', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('home_game', models.BooleanField(default=True)),
            ],
        ),
    ]
