# Generated by Django 6.0 on 2025-12-04 12:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=1, max_length=5, null=True)),
                ('position', models.CharField(blank=True, choices=[('Point Guard', 'Point Guard'), ('Shooting Guard', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=50, null=True)),
                ('jersey_number', models.PositiveIntegerField(unique=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Player Photo')),
            ],
            options={
                'verbose_name_plural': 'Players',
                'ordering': ['jersey_number'],
            },
        ),
    ]
