# Generated by Django 6.0 on 2025-12-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='New Player', max_length=100),
        ),
    ]
