# Generated by Django 6.0 on 2025-12-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_remove_player_first_name_remove_player_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='height',
            new_name='height_ft',
        ),
        migrations.AddField(
            model_name='player',
            name='weight_kgs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
