# Generated by Django 6.0 on 2025-12-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_rename_height_player_height_ft_player_weight_kgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height_ft',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight_kgs',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
