# Generated by Django 6.0 on 2025-12-06 07:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_alter_player_height_ft_alter_player_weight_kgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='height_ft',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in feet', max_digits=3, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload player image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight_kgs',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weight in kilograms', max_digits=5, null=True),
        ),
    ]
